import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import Header from "@/components/shared/header";
import { Providers } from "./providers";
import Footer from "@/components/shared/footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={cn(fontSans.variable)}>
          <Providers>
            <Toaster position="top-center" />
            <Header />
            <main>{children}</main>
            <Footer />
          </Providers>
        </body>
      </ClerkProvider>
    </html>
  );
}
